### PR TITLE
fix lambda deployment

### PR DESCRIPTION
**Pull request by rashadmoarref**
This PR fixes issue https://github.com/nficano/python-lambda/issues/711 by adding a waiter on `function_updated`.

### CODE REVIEW

**Comment by bokats** [comment]
@rashadmoarref Any idea when this will be merged. I am seeing the same issue.

**Comment by rashadmoarref** [comment]
@bokats I opened the PR, but would leave it for the repo maintainer to review and merge. @nficano, would you be able to review and merge this PR? I'm internally working with the fork I created and this PR resolves the deployment issue. Please let me know if you need additional information :)

**Comment by gdvalderrama** [comment]
Just tried these changes to get it to work.
Only needed the waiter, I guess the click version change is just a plus.

**Comment by Lowess** [comment]
Can we please get this ticket merged as it seems like everyone need to shift to this branch to get the project working ?

**Comment by rashadmoarref** [comment]
@nficano Could we move ahead with merging this PR? It will save a lot of time from other people coming up with the same solution, such as https://github.com/nficano/python-lambda/pull/716

**Pull request merged**
